<?xml version="1.0" standalone="yes"?>
<!-- logreq request file -->
<!-- logreq version 1.0 / dtd version 1.0 -->
<!-- Do not edit this file! -->
<!DOCTYPE requests [
  <!ELEMENT requests (internal | external)*>
  <!ELEMENT internal (generic, (provides | requires)*)>
  <!ELEMENT external (generic, cmdline?, input?, output?, (provides | requires)*)>
  <!ELEMENT cmdline (binary, (option | infile | outfile)*)>
  <!ELEMENT input (file)+>
  <!ELEMENT output (file)+>
  <!ELEMENT provides (file)+>
  <!ELEMENT requires (file)+>
  <!ELEMENT generic (#PCDATA)>
  <!ELEMENT binary (#PCDATA)>
  <!ELEMENT option (#PCDATA)>
  <!ELEMENT infile (#PCDATA)>
  <!ELEMENT outfile (#PCDATA)>
  <!ELEMENT file (#PCDATA)>
  <!ATTLIST requests
    version CDATA #REQUIRED
  >
  <!ATTLIST internal
    package CDATA #REQUIRED
    priority (9) #REQUIRED
    active (0 | 1) #REQUIRED
  >
  <!ATTLIST external
    package CDATA #REQUIRED
    priority (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) #REQUIRED
    active (0 | 1) #REQUIRED
  >
  <!ATTLIST provides
    type (static | dynamic | editable) #REQUIRED
  >
  <!ATTLIST requires
    type (static | dynamic | editable) #REQUIRED
  >
  <!ATTLIST file
    type CDATA #IMPLIED
  >
]>
<requests version="1.0">
  <internal package="biblatex" priority="9" active="0">
    <generic>latex</generic>
    <provides type="dynamic">
      <file>SRI-VSM-Mast-2-BOUDI.bcf</file>
    </provides>
    <requires type="dynamic">
      <file>SRI-VSM-Mast-2-BOUDI.bbl</file>
    </requires>
    <requires type="static">
      <file>blx-dm.def</file>
      <file>blx-compat.def</file>
      <file>biblatex.def</file>
      <file>blx-natbib.def</file>
      <file>standard.bbx</file>
      <file>authoryear.bbx</file>
      <file>authoryear.cbx</file>
      <file>biblatex.cfg</file>
      <file>french.lbx</file>
    </requires>
  </internal>
  <external package="biblatex" priority="5" active="0">
    <generic>biber</generic>
    <cmdline>
      <binary>biber</binary>
      <infile>SRI-VSM-Mast-2-BOUDI</infile>
    </cmdline>
    <input>
      <file>SRI-VSM-Mast-2-BOUDI.bcf</file>
    </input>
    <output>
      <file>SRI-VSM-Mast-2-BOUDI.bbl</file>
    </output>
    <provides type="dynamic">
      <file>SRI-VSM-Mast-2-BOUDI.bbl</file>
    </provides>
    <requires type="dynamic">
      <file>SRI-VSM-Mast-2-BOUDI.bcf</file>
    </requires>
    <requires type="editable">
      <file>Bibliography/Article.bib</file>
      <file>Bibliography/Book.bib</file>
      <file>Bibliography/Course.bib</file>
      <file>Bibliography/Inproceedings.bib</file>
      <file>Bibliography/Journal.bib</file>
      <file>Bibliography/Master-thesis.bib</file>
      <file>Bibliography/Phd-thesis.bib</file>
      <file>Bibliography/Website.bib</file>
      <file>Bibliography/Realisation/Website.bib</file>
    </requires>
  </external>
</requests>
